-d C:\Users\jjate\OneDrive\Desktop\riscv_soc\riscv_soc\impl\gwsynthesis\riscv_soc.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\jjate\OneDrive\Desktop\riscv_soc\riscv_soc\src\riscv_soc.cst
-cfg C:\Users\jjate\OneDrive\Desktop\riscv_soc\riscv_soc\impl\pnr\device.cfg
-sdc C:\Users\jjate\OneDrive\Desktop\riscv_soc\riscv_soc\src\riscv_soc.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
